### ISSUE TITLE
signed integer overflow bug in parsing

### ISSUE THREAD

**Issue by c42f373607bf2b** [kaitai-io/kaitai_struct_compiler#115]
```
meta:
  id: example
  endian: le

seq:
  - id: foo
    type: u4
  - id: node1 
    type:
      switch-on: foo
      cases:
        0x7fffffff: u4 # OK
        _: u8
  - id: node2 
    type:
      switch-on: foo
      cases:
        0x80000000: u4 # ERROR (signed overflow)
        _: u8
```

```
> ksc bug.ksy -t javascript
/seq/2/cases: expected string, got 2147483648 (class java.lang.Long)
```
