### ISSUE TITLE
ks-opaqe-types not working with imports

### ISSUE THREAD

**Issue by ii8** [kaitai-io/kaitai_struct_compiler#120]
`ks-opaque-types: true` seems to have no effect whenever there is an `imports` directive, even if they are completely unrelated.

#### Example:
filea.ksy:
```yaml
meta:
  id: filea
  ks-opaque-types: true
  imports:
    - fileb

seq:
  - id: a
    type: i_am_opaque
```
fileb.ksy:
```yaml
meta:
  id: fileb
```
command:
```
λ /usr/local/Cellar/kaitai-struct-compiler/0.7/bin/kaitai-struct-compiler --target graphviz filea.ksy

/seq/0: unable to find type 'i_am_opaque', searching from filea
```
