### ISSUE TITLE
Are relative positions supported for `pos'?

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_compiler#33]
In #32 I'm using `pos` to read some bytes and first tried to use negative offsets, which failed in Java and Ruby. Both stream abstractions don't support negative offsets.

https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#position(int)

Is there some supported syntax to move the position relative from the current position in the stream? This doesn't necessarily need to be supported by the compiler, one could easily calc the needed position itself in the KSY file. One would only need the "current position". But I couldn't anything in the Wiki for this.

I think of something like the following:

      prod_code_hr:
        pos:  _curPos - 8
        type: u2
        enum: prod_code_hr
        doc:  Better human readable version of the prod_code, using standardized 3 letters string.

This way you would at least not need to implement negative position calculation in all languages.

**Comment by GreyCat** [comment]
They are, if you use substreams. Usually you'd want to create a substream (limiting attribute with a `size`), and inside that limited substream you'll have its own indexing - starting with 0 at the beginning of whatever you've cut for a substream.

Simple example:

```yaml
meta:
  id: substream_example
  endian: le
seq:
  - id: junk
    size: 0x20
  - id: body
    size: 0x400 # ← this is important, this creates a substream
    type: substream_body
types:
  substream_body
    seq:
      - id: offset
        type: u4
    instances:
      the_thing:
        pos: offset
        # ^^^ this one is relative to beginning of substream_body,
        # not absolute (i.e. from the start of the file)
        type: u4
```
