### ISSUE TITLE
Make it possible to compare enum values with integers

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_compiler#74]
In the specification I'm implementing, there are fields which are present for specific ranges of enum value:

```
- id: tag
   type: u1
   enum: ast_tag
- id: cat1_nat
   type: nat
   if: tag < 64
```
it seems it's currently not supported:
```
KS compilation error:  io.kaitai.struct.translators.TypeMismatchError: can't compare EnumType(List(ast_tag),Int1Type(false)) and Int1Type(true)
```

**Comment by GreyCat** [comment]
This issue was already discussed once in https://github.com/kaitai-io/kaitai_struct/issues/98 — my proposal was to use something like:

```yaml
- id: tag
  type: u1
  enum: ast_tag
- id: cat1_nat
  type: nat
  if: tag.to_i < 64 # ← explicit conversion from EnumType to IntType
```
