### ISSUE TITLE
possibility to check if a value belongs to an enumeration

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_compiler#75]
something like:

```
seg:
  - id: tag
    type: u1
  - id: etc
    if: enum_known.contains(tag)
enums:
  enum_known:
    1: utf8
```
